import type { DispatchActivity, HuntActivity } from "@pieai/university-core";

import { interfaceTranslator } from "../i18n/index.js";

/** Fresh translated payloads; no lesson production or progress state lives here. */
export function extraExamples(): readonly (HuntActivity | DispatchActivity)[] {
  const shipping: HuntActivity = {
    id: "hunt-shipping",
    kind: "hunt",
    title: interfaceTranslator.t("play.extra.sample.shipping.title"),
    brief: interfaceTranslator.t("play.extra.sample.shipping.brief"),
    goal: interfaceTranslator.t("play.extra.sample.shipping.goal"),
    takeaway: interfaceTranslator.t("play.extra.sample.shipping.takeaway"),
    hint: interfaceTranslator.t("play.extra.sample.shipping.hint"),
    source: {
      label: interfaceTranslator.t("play.extra.sample.shipping.source"),
      url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Greater_than_or_equal",
    },
    model: "threshold",
    boundary: 100,
    input: {
      label: interfaceTranslator.t("play.extra.sample.shipping.input"),
      unit: interfaceTranslator.t("play.extra.sample.shipping.unit"),
      min: 0,
      max: 200,
      initial: 120,
    },
    rule: interfaceTranslator.t("play.extra.sample.shipping.rule"),
    program: interfaceTranslator.t("play.extra.sample.shipping.program"),
    outputLabel: interfaceTranslator.t("play.extra.sample.shipping.output"),
  };
  const volume: HuntActivity = {
    id: "hunt-volume",
    kind: "hunt",
    title: interfaceTranslator.t("play.extra.sample.volume.title"),
    brief: interfaceTranslator.t("play.extra.sample.volume.brief"),
    goal: interfaceTranslator.t("play.extra.sample.volume.goal"),
    takeaway: interfaceTranslator.t("play.extra.sample.volume.takeaway"),
    hint: interfaceTranslator.t("play.extra.sample.volume.hint"),
    source: {
      label: interfaceTranslator.t("play.extra.sample.volume.source"),
      url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/max",
    },
    model: "clamp",
    boundary: 100,
    input: {
      label: interfaceTranslator.t("play.extra.sample.volume.input"),
      unit: interfaceTranslator.t("play.extra.sample.volume.unit"),
      min: -100,
      max: 200,
      initial: 40,
    },
    rule: interfaceTranslator.t("play.extra.sample.volume.rule"),
    program: interfaceTranslator.t("play.extra.sample.volume.program"),
    outputLabel: interfaceTranslator.t("play.extra.sample.volume.output"),
  };
  const website: DispatchActivity = {
    id: "dispatch-website",
    kind: "dispatch",
    title: interfaceTranslator.t("play.extra.sample.web.title"),
    brief: interfaceTranslator.t("play.extra.sample.web.brief"),
    goal: interfaceTranslator.t("play.extra.sample.web.goal"),
    takeaway: interfaceTranslator.t("play.extra.sample.web.takeaway"),
    hint: interfaceTranslator.t("play.extra.sample.web.hint"),
    source: {
      label: interfaceTranslator.t("play.extra.sample.web.source"),
      url: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Caching",
    },
    cacheLaneId: "cache",
    budget: 8,
    seconds: 60,
    lanes: [
      {
        id: "cache",
        label: interfaceTranslator.t("play.extra.sample.web.cache"),
        note: interfaceTranslator.t("play.extra.sample.web.cacheNote"),
        cost: 0,
      },
      {
        id: "static",
        label: interfaceTranslator.t("play.extra.sample.web.static"),
        note: interfaceTranslator.t("play.extra.sample.web.staticNote"),
        cost: 1,
      },
      {
        id: "live",
        label: interfaceTranslator.t("play.extra.sample.web.live"),
        note: interfaceTranslator.t("play.extra.sample.web.liveNote"),
        cost: 3,
      },
    ],
    cards: [
      {
        id: "poster-1",
        label: interfaceTranslator.t("play.extra.sample.web.hero"),
        detail: interfaceTranslator.t("play.extra.sample.web.heroDetail"),
        allowedLaneIds: ["static", "live"],
        cacheKey: "poster-v1",
        why: interfaceTranslator.t("play.extra.sample.web.fileWhy"),
      },
      {
        id: "price",
        label: interfaceTranslator.t("play.extra.sample.web.price"),
        detail: interfaceTranslator.t("play.extra.sample.web.priceDetail"),
        allowedLaneIds: ["live"],
        why: interfaceTranslator.t("play.extra.sample.web.liveWhy"),
      },
      {
        id: "styles-1",
        label: interfaceTranslator.t("play.extra.sample.web.css"),
        detail: interfaceTranslator.t("play.extra.sample.web.cssDetail"),
        allowedLaneIds: ["static", "live"],
        cacheKey: "theme-v2",
        why: interfaceTranslator.t("play.extra.sample.web.fileWhy"),
      },
      {
        id: "poster-2",
        label: interfaceTranslator.t("play.extra.sample.web.heroRepeat"),
        detail: interfaceTranslator.t("play.extra.sample.web.heroDetail"),
        allowedLaneIds: ["static", "live"],
        cacheKey: "poster-v1",
        why: interfaceTranslator.t("play.extra.sample.web.fileWhy"),
      },
      {
        id: "stock",
        label: interfaceTranslator.t("play.extra.sample.web.stock"),
        detail: interfaceTranslator.t("play.extra.sample.web.stockDetail"),
        allowedLaneIds: ["live"],
        why: interfaceTranslator.t("play.extra.sample.web.liveWhy"),
      },
      {
        id: "styles-2",
        label: interfaceTranslator.t("play.extra.sample.web.cssRepeat"),
        detail: interfaceTranslator.t("play.extra.sample.web.cssDetail"),
        allowedLaneIds: ["static", "live"],
        cacheKey: "theme-v2",
        why: interfaceTranslator.t("play.extra.sample.web.fileWhy"),
      },
      {
        id: "poster-3",
        label: interfaceTranslator.t("play.extra.sample.web.heroRepeat"),
        detail: interfaceTranslator.t("play.extra.sample.web.heroDetail"),
        allowedLaneIds: ["static", "live"],
        cacheKey: "poster-v1",
        why: interfaceTranslator.t("play.extra.sample.web.fileWhy"),
      },
    ],
  };
  const video: DispatchActivity = {
    id: "dispatch-video",
    kind: "dispatch",
    title: interfaceTranslator.t("play.extra.sample.video.title"),
    brief: interfaceTranslator.t("play.extra.sample.video.brief"),
    goal: interfaceTranslator.t("play.extra.sample.video.goal"),
    takeaway: interfaceTranslator.t("play.extra.sample.video.takeaway"),
    hint: interfaceTranslator.t("play.extra.sample.video.hint"),
    source: {
      label: interfaceTranslator.t("play.extra.sample.video.source"),
      url: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Caching",
    },
    cacheLaneId: "cache",
    budget: 8,
    seconds: 60,
    lanes: [
      {
        id: "cache",
        label: interfaceTranslator.t("play.extra.sample.video.cache"),
        note: interfaceTranslator.t("play.extra.sample.video.cacheNote"),
        cost: 0,
      },
      {
        id: "library",
        label: interfaceTranslator.t("play.extra.sample.video.library"),
        note: interfaceTranslator.t("play.extra.sample.video.libraryNote"),
        cost: 1,
      },
      {
        id: "studio",
        label: interfaceTranslator.t("play.extra.sample.video.studio"),
        note: interfaceTranslator.t("play.extra.sample.video.studioNote"),
        cost: 3,
      },
    ],
    cards: [
      {
        id: "music-1",
        label: interfaceTranslator.t("play.extra.sample.video.music"),
        detail: interfaceTranslator.t("play.extra.sample.video.musicDetail"),
        allowedLaneIds: ["library", "studio"],
        cacheKey: "music-v1",
        why: interfaceTranslator.t("play.extra.sample.video.fileWhy"),
      },
      {
        id: "captions-1",
        label: interfaceTranslator.t("play.extra.sample.video.captions"),
        detail: interfaceTranslator.t("play.extra.sample.video.captionDetail"),
        allowedLaneIds: ["studio"],
        cacheKey: "caption-v1",
        why: interfaceTranslator.t("play.extra.sample.video.captionWhy"),
      },
      {
        id: "logo-1",
        label: interfaceTranslator.t("play.extra.sample.video.logo"),
        detail: interfaceTranslator.t("play.extra.sample.video.logoDetail"),
        allowedLaneIds: ["library", "studio"],
        cacheKey: "logo-v3",
        why: interfaceTranslator.t("play.extra.sample.video.fileWhy"),
      },
      {
        id: "music-2",
        label: interfaceTranslator.t("play.extra.sample.video.musicRepeat"),
        detail: interfaceTranslator.t("play.extra.sample.video.musicDetail"),
        allowedLaneIds: ["library", "studio"],
        cacheKey: "music-v1",
        why: interfaceTranslator.t("play.extra.sample.video.fileWhy"),
      },
      {
        id: "progress",
        label: interfaceTranslator.t("play.extra.sample.video.progress"),
        detail: interfaceTranslator.t("play.extra.sample.video.progressDetail"),
        allowedLaneIds: ["studio"],
        why: interfaceTranslator.t("play.extra.sample.video.progressWhy"),
      },
      {
        id: "captions-2",
        label: interfaceTranslator.t("play.extra.sample.video.captionRepeat"),
        detail: interfaceTranslator.t("play.extra.sample.video.captionRepeatDetail"),
        allowedLaneIds: ["studio"],
        cacheKey: "caption-v1",
        why: interfaceTranslator.t("play.extra.sample.video.captionWhy"),
      },
      {
        id: "logo-2",
        label: interfaceTranslator.t("play.extra.sample.video.logoRepeat"),
        detail: interfaceTranslator.t("play.extra.sample.video.logoDetail"),
        allowedLaneIds: ["library", "studio"],
        cacheKey: "logo-v3",
        why: interfaceTranslator.t("play.extra.sample.video.fileWhy"),
      },
    ],
  };
  return [shipping, volume, website, video];
}
