// Generated by swimmer-i18n-check types. Do not edit.
export interface MessageContracts {
  readonly "billing.free.line1": {  };
  readonly "billing.free.line2": {  };
  readonly "billing.free.line3": {  };
  readonly "billing.free.name": {  };
  readonly "billing.member.line1": {  };
  readonly "billing.member.line2": {  };
  readonly "billing.member.line3": {  };
  readonly "billing.member.name": {  };
  readonly "grading.free.count": { readonly "amount": string | number | bigint | boolean | null | undefined | Date; readonly "count": number; };
  readonly "grading.free.unavailable": {  };
  readonly "grading.free.zero": {  };
  readonly "grading.host.ai": {  };
  readonly "grading.host.automatic": {  };
  readonly "grading.quantity.count": { readonly "amount": string | number | bigint | boolean | null | undefined | Date; readonly "count": number; };
  readonly "grading.quantity.unavailable": {  };
  readonly "grading.quantity.zero": {  };
  readonly "grading.wallet.count": { readonly "amount": string | number | bigint | boolean | null | undefined | Date; readonly "count": number; };
  readonly "grading.wallet.unavailable": {  };
  readonly "grading.wallet.zero": {  };
}
