import type { ConceptHead } from "../domain/concept.js";

/**
 * Names and taglines only. Bodies stay in `catalogue.ts`.
 *
 * LoadingTrivia needs a sentence on the first frame; it does not need 1.6MB of
 * illustrated entries. `catalogue.test.ts` asserts this list matches
 * `CONCEPT_ENTRIES.map((entry) => entry.head)`, so a new entry that forgets
 * this file fails CI rather than showing an old shelf.
 */
export const CONCEPT_HEADS: readonly ConceptHead[] = [
  {
    id: "frontend",
    zh: "前端",
    en: "Frontend",
    category: "frontend",
    group: "网页基础",
    tagline: "你在网页上看到、点到、填进去的那一层。",
  },
  {
    id: "component",
    zh: "组件",
    en: "Component",
    category: "frontend",
    group: "网页基础",
    tagline: "改一处，所有用到它的地方一起变的那块界面。",
  },
  {
    id: "state",
    zh: "状态",
    en: "State",
    category: "frontend",
    group: "网页基础",
    tagline: "界面此刻必须记住、而且会跟着操作变的信息。",
  },
  {
    id: "markdown",
    zh: "Markdown",
    en: "",
    category: "frontend",
    group: "网页基础",
    tagline: "用少量符号标明标题、列表和代码的纯文本。",
  },
  {
    id: "html",
    zh: "HTML",
    en: "",
    category: "frontend",
    group: "网页基础",
    tagline: "给网页每一块内容贴上「这是什么」的标签。",
  },
  {
    id: "css",
    zh: "CSS",
    en: "",
    category: "frontend",
    group: "网页基础",
    tagline: "管网页颜色、字体、间距和排法的那套规则。",
  },
  {
    id: "dom",
    zh: "文档对象模型",
    en: "DOM",
    category: "frontend",
    group: "网页基础",
    tagline: "浏览器此刻手里的页面结构，不是硬盘上的文件。",
  },
  {
    id: "title-tag",
    zh: "页面标题",
    en: "Title Tag",
    category: "frontend",
    group: "网页基础",
    tagline: "浏览器标签上那行字，用来认出你打开的是哪一页。",
  },
  {
    id: "page-metadata",
    zh: "页面元数据",
    en: "Page Metadata",
    category: "frontend",
    group: "网页基础",
    tagline: "写给浏览器和分享软件看、正文里不一定出现的说明。",
  },
  {
    id: "favicon",
    zh: "网站图标",
    en: "Favicon",
    category: "frontend",
    group: "网页基础",
    tagline: "浏览器标签和书签上那枚用来认站的小图标。",
  },
  {
    id: "open-graph",
    zh: "Open Graph",
    en: "",
    category: "frontend",
    group: "网页基础",
    tagline: "聊天软件生成链接预览卡时读取的那几项说明。",
  },
  {
    id: "web-app-manifest",
    zh: "Web 应用清单",
    en: "Web App Manifest",
    category: "frontend",
    group: "网页基础",
    tagline: "告诉手机：名称、图标、点开后进哪一页的那份说明。",
  },
  {
    id: "undo",
    zh: "撤销",
    en: "Undo",
    category: "frontend",
    group: "网页基础",
    tagline: "把刚做的那一步原样退回去，不用重做一遍。",
  },
  {
    id: "accessibility",
    zh: "无障碍",
    en: "Accessibility",
    category: "frontend",
    group: "网页基础",
    tagline: "让更多人在更多情况下都能用你的页面。",
  },
  {
    id: "button",
    zh: "按钮",
    en: "Button",
    category: "frontend",
    group: "按钮与链接",
    tagline: "点一下就在当前这一页把事情做掉的可点区域。",
  },
  {
    id: "link",
    zh: "链接",
    en: "Link",
    category: "frontend",
    group: "按钮与链接",
    tagline: "点一下把你带到别处，地址栏会跟着变。",
  },
  {
    id: "input",
    zh: "输入框",
    en: "Input",
    category: "frontend",
    group: "表单",
    tagline: "一次打一行字的格子，比如姓名、手机号。",
  },
  {
    id: "textarea",
    zh: "多行文本框",
    en: "Textarea",
    category: "frontend",
    group: "表单",
    tagline: "能换行、能打一段话的那块大输入区。",
  },
  {
    id: "input-number",
    zh: "数字输入框",
    en: "InputNumber",
    category: "frontend",
    group: "表单",
    tagline: "只接受数字，常带加减，用来填个数和数量。",
  },
  {
    id: "radio",
    zh: "单选框",
    en: "Radio",
    category: "frontend",
    group: "表单",
    tagline: "选项不多、全部摊开，一次只能选一个。",
  },
  {
    id: "checkbox",
    zh: "复选框",
    en: "Checkbox",
    category: "frontend",
    group: "表单",
    tagline: "小方框，能勾上多个，也能一个都不勾。",
  },
  {
    id: "switch",
    zh: "开关",
    en: "Switch",
    category: "frontend",
    group: "表单",
    tagline: "拨一下当场开或关，不用再点保存。",
  },
  {
    id: "slider",
    zh: "滑块",
    en: "Slider",
    category: "frontend",
    group: "表单",
    tagline: "拖一下，在一段范围内选出一个大概的值。",
  },
  {
    id: "rate",
    zh: "评分",
    en: "Rate",
    category: "frontend",
    group: "表单",
    tagline: "用几颗星给好坏打分，不是收藏那颗星。",
  },
  {
    id: "select",
    zh: "选择器",
    en: "Select",
    category: "frontend",
    group: "表单",
    tagline: "点开一长串名单，从里面挑一项。",
  },
  {
    id: "auto-complete",
    zh: "自动完成",
    en: "AutoComplete",
    category: "frontend",
    group: "表单",
    tagline: "边打字，边弹出可能匹配的现成选项。",
  },
  {
    id: "cascader",
    zh: "级联选择器",
    en: "Cascader",
    category: "frontend",
    group: "表单",
    tagline: "一层层往下选，上一层决定下一层有什么。",
  },
  {
    id: "tree-select",
    zh: "树选择",
    en: "TreeSelect",
    category: "frontend",
    group: "表单",
    tagline: "从一层套一层的名单里勾选，可选中间那一层。",
  },
  {
    id: "date-picker",
    zh: "日期选择器",
    en: "DatePicker",
    category: "frontend",
    group: "表单",
    tagline: "从日历上点选日期，不要自己敲格式。",
  },
  {
    id: "time-picker",
    zh: "时间选择器",
    en: "TimePicker",
    category: "frontend",
    group: "表单",
    tagline: "从钟点列表里选出一天里的某个时刻。",
  },
  {
    id: "upload",
    zh: "上传",
    en: "Upload",
    category: "frontend",
    group: "表单",
    tagline: "从这台设备挑文件，发到网站那一头。",
  },
  {
    id: "form",
    zh: "表单",
    en: "Form",
    category: "frontend",
    group: "表单",
    tagline: "若干要填的格子，加上「提交」这一整份。",
  },
  {
    id: "color-picker",
    zh: "颜色选择器",
    en: "ColorPicker",
    category: "frontend",
    group: "表单",
    tagline: "从色板或取色器里选出一个颜色。",
  },
  {
    id: "label",
    zh: "表单标签",
    en: "Label",
    category: "frontend",
    group: "表单",
    tagline: "写在格子旁边、说明这一格是什么的字。",
  },
  {
    id: "placeholder",
    zh: "占位文字",
    en: "Placeholder",
    category: "frontend",
    group: "表单",
    tagline: "框还空着时，里面那行浅色提示。",
  },
  {
    id: "table",
    zh: "表格",
    en: "Table",
    category: "frontend",
    group: "内容展示",
    tagline: "一行一条、一列一个栏目，方便拿多条对着比。",
  },
  {
    id: "list",
    zh: "列表",
    en: "List",
    category: "frontend",
    group: "内容展示",
    tagline: "结构相同的一条条，从上往下排，不拿多列对着比。",
  },
  {
    id: "card",
    zh: "卡片",
    en: "Card",
    category: "frontend",
    group: "内容展示",
    tagline: "一张块里装同一个对象的图、标题和动作。",
  },
  {
    id: "tag",
    zh: "标签",
    en: "Tag",
    category: "frontend",
    group: "内容展示",
    tagline: "贴在内容旁边的短标记，说明类别或状态。",
  },
  {
    id: "badge",
    zh: "徽标",
    en: "Badge",
    category: "frontend",
    group: "内容展示",
    tagline: "贴在别的东西角落上的小数字或小圆点。",
  },
  {
    id: "avatar",
    zh: "头像",
    en: "Avatar",
    category: "frontend",
    group: "内容展示",
    tagline: "用来认人的小图，旁边通常还要写名字。",
  },
  {
    id: "descriptions",
    zh: "描述列表",
    en: "Descriptions",
    category: "frontend",
    group: "内容展示",
    tagline: "一条记录的「栏目名 + 内容」，给人看不给人改。",
  },
  {
    id: "statistic",
    zh: "统计数值",
    en: "Statistic",
    category: "frontend",
    group: "内容展示",
    tagline: "把一个关键数字放大，并写清这是什么、跟谁比。",
  },
  {
    id: "tabs",
    zh: "标签页",
    en: "Tabs",
    category: "frontend",
    group: "内容展示",
    tagline: "同一页里点页签，切换几组没有先后的内容。",
  },
  {
    id: "segmented",
    zh: "分段控件",
    en: "Segmented",
    category: "frontend",
    group: "内容展示",
    tagline: "两三个短选项并排，点哪个就换成哪种看法。",
  },
  {
    id: "collapse",
    zh: "折叠面板",
    en: "Collapse",
    category: "frontend",
    group: "内容展示",
    tagline: "先只露标题，点开再看里面的详细内容。",
  },
  {
    id: "timeline",
    zh: "时间轴",
    en: "Timeline",
    category: "frontend",
    group: "内容展示",
    tagline: "已经发生的事按时间排成一串，看先到哪一步。",
  },
  {
    id: "tree",
    zh: "树形控件",
    en: "Tree",
    category: "frontend",
    group: "内容展示",
    tagline: "一层套一层，点小三角展开下一级。",
  },
  {
    id: "carousel",
    zh: "走马灯",
    en: "Carousel",
    category: "frontend",
    group: "内容展示",
    tagline: "同一块地方轮流看几张图，能自己翻也能看第几张。",
  },
  {
    id: "empty",
    zh: "空状态",
    en: "Empty",
    category: "frontend",
    group: "内容展示",
    tagline: "这里本来该有内容，现在没有，说明原因和下一步。",
  },
  {
    id: "image",
    zh: "图片",
    en: "Image",
    category: "frontend",
    group: "内容展示",
    tagline: "网页上的一张静止画面：照片、配图、封面。",
  },
  {
    id: "file",
    zh: "文件项",
    en: "File",
    category: "frontend",
    group: "内容展示",
    tagline: "已经选中或传上来的一份文件：名字、大小、状态。",
  },
  {
    id: "icon",
    zh: "图标",
    en: "Icon",
    category: "frontend",
    group: "内容展示",
    tagline: "界面上反复出现的小图形，表示一个功能或状态。",
  },
  {
    id: "quote",
    zh: "引用",
    en: "Quote",
    category: "frontend",
    group: "内容展示",
    tagline: "从正文里单独拿出来、并标明是谁说的原话。",
  },
  {
    id: "video",
    zh: "视频",
    en: "Video",
    category: "frontend",
    group: "内容展示",
    tagline: "能播放的一段连续画面，有进度、有声音、有暂停。",
  },
  {
    id: "chat-ui",
    zh: "聊天界面",
    en: "Chat UI",
    category: "frontend",
    group: "内容展示",
    tagline: "一问一答那扇窗：消息列表、输入框、发送状态。",
  },
  {
    id: "filter",
    zh: "筛选",
    en: "Filter",
    category: "frontend",
    group: "内容展示",
    tagline: "按已有条件把不符合的藏起来，列表会变短。",
  },
  {
    id: "chart",
    zh: "图表",
    en: "Chart",
    category: "frontend",
    group: "内容展示",
    tagline: "用柱子高低、线的走势让人看出数据和数据的差别。",
  },
  {
    id: "app-icon",
    zh: "应用图标",
    en: "App Icon",
    category: "frontend",
    group: "内容展示",
    tagline: "手机主屏幕上那颗代表整个应用的方形图。",
  },
  {
    id: "sort",
    zh: "排序",
    en: "Sort",
    category: "frontend",
    group: "内容展示",
    tagline: "不减少条数，只按某个栏目把先后换一下。",
  },
  {
    id: "alert",
    zh: "警告提示",
    en: "Alert",
    category: "frontend",
    group: "弹窗与提示",
    tagline: "贴在页面上、一直留着，直到那件事过去。",
  },
  {
    id: "toast",
    zh: "轻提示",
    en: "Toast",
    category: "frontend",
    group: "弹窗与提示",
    tagline: "角落里闪一句「做成了」，自己会消失。",
  },
  {
    id: "notification",
    zh: "通知",
    en: "Notification",
    category: "frontend",
    group: "弹窗与提示",
    tagline: "可以稍后打开的消息，常常会堆成一叠。",
  },
  {
    id: "modal",
    zh: "弹窗",
    en: "Modal",
    category: "frontend",
    group: "弹窗与提示",
    tagline: "挡住整页、必须先处理完才能回去的那块盒子。",
  },
  {
    id: "drawer",
    zh: "抽屉",
    en: "Drawer",
    category: "frontend",
    group: "弹窗与提示",
    tagline: "从边上滑出来的面板，底下那一页还在。",
  },
  {
    id: "popconfirm",
    zh: "气泡确认框",
    en: "Popconfirm",
    category: "frontend",
    group: "弹窗与提示",
    tagline: "点了危险动作，贴在旁边再问一句确定吗。",
  },
  {
    id: "popover",
    zh: "气泡卡片",
    en: "Popover",
    category: "frontend",
    group: "弹窗与提示",
    tagline: "贴在某个词或按钮旁边的小卡片，里面可以有按钮。",
  },
  {
    id: "tooltip",
    zh: "文字提示",
    en: "Tooltip",
    category: "frontend",
    group: "弹窗与提示",
    tagline: "停上去才出现的一小句说明，里面没有按钮。",
  },
  {
    id: "progress",
    zh: "进度条",
    en: "Progress",
    category: "frontend",
    group: "弹窗与提示",
    tagline: "用一条在变长的杠，告诉你这件事做到哪了。",
  },
  {
    id: "skeleton",
    zh: "骨架屏",
    en: "Skeleton",
    category: "frontend",
    group: "弹窗与提示",
    tagline: "还在取内容时，先用灰块把页面形状撑住。",
  },
  {
    id: "result",
    zh: "结果页",
    en: "Result",
    category: "frontend",
    group: "弹窗与提示",
    tagline: "一整步走完后，单独告诉你成了还是没成。",
  },
  {
    id: "spinner",
    zh: "旋转加载指示器",
    en: "Spinner",
    category: "frontend",
    group: "弹窗与提示",
    tagline: "转圈，表示还在做、先等一下。",
  },
  {
    id: "menu",
    zh: "导航菜单",
    en: "Menu",
    category: "frontend",
    group: "导航",
    tagline: "一列或一排去处，告诉你现在能去哪。",
  },
  {
    id: "breadcrumb",
    zh: "面包屑",
    en: "Breadcrumb",
    category: "frontend",
    group: "导航",
    tagline: "一串上一级，告诉你现在在哪一层、怎么往回走。",
  },
  {
    id: "pagination",
    zh: "分页",
    en: "Pagination",
    category: "frontend",
    group: "导航",
    tagline: "把一长串拆成第 1 页、第 2 页，一次只看一截。",
  },
  {
    id: "steps",
    zh: "步骤条",
    en: "Steps",
    category: "frontend",
    group: "导航",
    tagline: "把一件大事拆成几步，标出你现在走到第几步。",
  },
  {
    id: "dropdown",
    zh: "下拉菜单",
    en: "Dropdown",
    category: "frontend",
    group: "导航",
    tagline: "点一下才垂下来的清单，用来挑一个动作或去处。",
  },
  {
    id: "anchor",
    zh: "锚点",
    en: "Anchor",
    category: "frontend",
    group: "导航",
    tagline: "点了滚到本页某一段，地址栏带上那一段的记号。",
  },
  {
    id: "back-top",
    zh: "回到顶部",
    en: "BackTop",
    category: "frontend",
    group: "导航",
    tagline: "滚下去之后出现的按钮，一点回到最上面。",
  },
  {
    id: "skip-link",
    zh: "跳过导航链接",
    en: "SkipLink",
    category: "frontend",
    group: "导航",
    tagline: "键盘一上来就能跳过栏目，直接进正文。",
  },
  {
    id: "search",
    zh: "搜索",
    en: "Search",
    category: "frontend",
    group: "导航",
    tagline: "打几个字，把对得上的那几条找出来。",
  },
  {
    id: "hero",
    zh: "首屏",
    en: "Hero",
    category: "frontend",
    group: "官网区块",
    tagline: "打开网站、不用往下滚就能看见的那一整块介绍。",
  },
  {
    id: "cta",
    zh: "CTA",
    en: "",
    category: "frontend",
    group: "官网区块",
    tagline: "当前这一块最想让人立刻去做的那一下。",
  },
  {
    id: "user-voice",
    zh: "用户原声",
    en: "UserVoice",
    category: "frontend",
    group: "官网区块",
    tagline: "把用户自己说过的话原样放出来，不当文案改。",
  },
  {
    id: "header",
    zh: "页头",
    en: "Header",
    category: "frontend",
    group: "官网区块",
    tagline: "每一页最顶端那一条：标志、栏目，有时还有主按钮。",
  },
  {
    id: "logo",
    zh: "标志",
    en: "Logo",
    category: "frontend",
    group: "官网区块",
    tagline: "用来认出「这是谁的网站」的那个图或字。",
  },
  {
    id: "navbar",
    zh: "顶部导航栏",
    en: "Navbar",
    category: "frontend",
    group: "官网区块",
    tagline: "页头里那一行可点的栏目，用来在页面之间跳。",
  },
  {
    id: "footer",
    zh: "页脚",
    en: "Footer",
    category: "frontend",
    group: "官网区块",
    tagline: "滚到最底下那一块，放版权、备案和次要链接。",
  },
  {
    id: "faq",
    zh: "FAQ",
    en: "",
    category: "frontend",
    group: "官网区块",
    tagline: "把人真正会问的问题摊开，答案先说结论。",
  },
  {
    id: "pricing",
    zh: "定价区",
    en: "Pricing",
    category: "frontend",
    group: "官网区块",
    tagline: "把多少钱、包含什么、不包含什么摊在同一区。",
  },
  {
    id: "social-proof",
    zh: "社会证明",
    en: "SocialProof",
    category: "frontend",
    group: "官网区块",
    tagline: "用外人能核对的事实，证明这不是你自说自话。",
  },
  {
    id: "top-nav-layout",
    zh: "顶部导航布局",
    en: "Top Nav",
    category: "frontend",
    group: "页面布局",
    tagline: "上面一条导航、下面全是内容的整页排法。",
  },
  {
    id: "sidebar-layout",
    zh: "左侧栏布局",
    en: "Sidebar",
    category: "frontend",
    group: "页面布局",
    tagline: "左边一列导航、右边放大块内容的整页排法。",
  },
  {
    id: "single-page-layout",
    zh: "单页滚动布局",
    en: "Single Page",
    category: "frontend",
    group: "页面布局",
    tagline: "介绍、价格、报名接在一页里，靠往下滚看完。",
  },
  {
    id: "doc-layout",
    zh: "文档三栏布局",
    en: "Doc Layout",
    category: "frontend",
    group: "页面布局",
    tagline: "左目录、中正文、右本页大纲的阅读排法。",
  },
  {
    id: "card-grid-layout",
    zh: "卡片网格布局",
    en: "Card Grid",
    category: "frontend",
    group: "页面布局",
    tagline: "同样结构的卡片按格子铺开的整页排法。",
  },
  {
    id: "centered-layout",
    zh: "居中窄栏布局",
    en: "Centered Column",
    category: "frontend",
    group: "页面布局",
    tagline: "中间一列窄正文、两边留白的阅读排法。",
  },
  {
    id: "masonry-layout",
    zh: "瀑布流",
    en: "Masonry",
    category: "frontend",
    group: "页面布局",
    tagline: "卡片高度不齐、像砌砖一样错落的铺法。",
  },
  {
    id: "split-screen-layout",
    zh: "分屏布局",
    en: "Split-screen",
    category: "frontend",
    group: "页面布局",
    tagline: "一屏左右两半、各放一件事的排法。",
  },
  {
    id: "responsive-design",
    zh: "响应式设计",
    en: "Responsive Design",
    category: "frontend",
    group: "页面布局",
    tagline: "同一网站在手机和电脑上改排法，不是整页缩小。",
  },
  {
    id: "space",
    zh: "间距",
    en: "Space",
    category: "frontend",
    group: "CSS 布局",
    tagline: "相关的挨着、无关的空开，整页用同一套空。",
  },
  {
    id: "margin",
    zh: "外边距",
    en: "Margin",
    category: "frontend",
    group: "CSS 布局",
    tagline: "盒子外面那圈透明的空，用来推开旁边的东西。",
  },
  {
    id: "padding",
    zh: "内边距",
    en: "Padding",
    category: "frontend",
    group: "CSS 布局",
    tagline: "盒子里面、内容和边之间的那圈空。",
  },
  {
    id: "flex",
    zh: "弹性布局",
    en: "Flex",
    category: "frontend",
    group: "CSS 布局",
    tagline: "沿一条线排：一排按钮或一列字段，空由这一组自己分。",
  },
  {
    id: "grid",
    zh: "网格布局",
    en: "Grid",
    category: "frontend",
    group: "CSS 布局",
    tagline: "按行和列同时对齐，适合卡片墙和整齐的表单。",
  },
  {
    id: "z-index",
    zh: "层级",
    en: "Z-Index",
    category: "frontend",
    group: "CSS 布局",
    tagline: "谁叠在谁上面。数字越大越靠前。",
  },
  {
    id: "sticky",
    zh: "吸顶",
    en: "Sticky",
    category: "frontend",
    group: "CSS 布局",
    tagline: "滚到它就贴在屏幕边上，滚出那一块就离开。",
  },
  {
    id: "position",
    zh: "定位",
    en: "Position",
    category: "frontend",
    group: "CSS 布局",
    tagline: "一块是排队往下排，还是拿出来贴到某个角。",
  },
  {
    id: "centering",
    zh: "居中",
    en: "Centering",
    category: "frontend",
    group: "CSS 布局",
    tagline: "把字或一整块放到中间：可以水平、上下或正中。",
  },
  {
    id: "box-model",
    zh: "盒模型",
    en: "Box Model",
    category: "frontend",
    group: "CSS 布局",
    tagline: "每块都是盒子：内容、内空、边框、外空。",
  },
  {
    id: "overflow",
    zh: "内容溢出",
    en: "Overflow",
    category: "frontend",
    group: "CSS 布局",
    tagline: "装不下时：露出来、剪掉，还是在盒子里滚。",
  },
  {
    id: "typography",
    zh: "排版",
    en: "Typography",
    category: "frontend",
    group: "文字",
    tagline: "字号、行距、行长和粗细怎么配合，才能读完。",
  },
  {
    id: "serif-sans",
    zh: "衬线与非衬线",
    en: "Serif & Sans",
    category: "frontend",
    group: "文字",
    tagline: "字有没有小脚：有脚偏长文，没脚偏按钮。",
  },
  {
    id: "text-truncate",
    zh: "文本截断",
    en: "Text Truncate",
    category: "frontend",
    group: "文字",
    tagline: "放不下就收成省略号，但得能看到被切掉的字。",
  },
  {
    id: "divider",
    zh: "分割线",
    en: "Divider",
    category: "frontend",
    group: "外观",
    tagline: "两组内容之间那根细线，用来分开，不是当装饰。",
  },
  {
    id: "border-radius",
    zh: "圆角",
    en: "BorderRadius",
    category: "frontend",
    group: "外观",
    tagline: "把盒子四个尖角磨圆，看起来软一点、没那么冲。",
  },
  {
    id: "shadow",
    zh: "阴影",
    en: "Shadow",
    category: "frontend",
    group: "外观",
    tagline: "盒子底下那圈淡影子，用来垫高，不是把页面涂脏。",
  },
  {
    id: "opacity",
    zh: "透明度",
    en: "Opacity",
    category: "frontend",
    group: "外观",
    tagline: "把整块连同里面的字一起调淡，后面的东西会透出来。",
  },
  {
    id: "gradient",
    zh: "渐变",
    en: "Gradient",
    category: "frontend",
    group: "外观",
    tagline: "颜色从一头慢慢过渡到另一头，不是一整块纯色。",
  },
  {
    id: "corner-feel",
    zh: "圆角的气质",
    en: "Corner Feel",
    category: "frontend",
    group: "外观",
    tagline: "全站圆多重，会让人觉得你像银行还是像玩具。",
  },
  {
    id: "backdrop-blur",
    zh: "毛玻璃",
    en: "Backdrop Blur",
    category: "frontend",
    group: "外观",
    tagline: "把后面透出来的画面抹糊，自己这一层还半透明。",
  },
  {
    id: "dark-mode",
    zh: "深色模式",
    en: "Dark Mode",
    category: "frontend",
    group: "外观",
    tagline: "整页换成深底浅字，不是只把背景涂黑、字还是黑的。",
  },
  {
    id: "design-token",
    zh: "设计令牌",
    en: "Design Token",
    category: "frontend",
    group: "外观",
    tagline: "给颜色、空、圆角起名字，整站共用，改一处全跟着换。",
  },
  {
    id: "contrast",
    zh: "对比度",
    en: "Contrast",
    category: "frontend",
    group: "外观",
    tagline: "字和它贴着的底差得够不够大，差太小就看不清。",
  },
  {
    id: "visual-hierarchy",
    zh: "视觉层级",
    en: "Visual Hierarchy",
    category: "frontend",
    group: "外观",
    tagline: "谁大谁重谁先被看见，让眼睛自己排出阅读顺序。",
  },
  {
    id: "transition",
    zh: "过渡",
    en: "Transition",
    category: "frontend",
    group: "动画",
    tagline: "从一个样子平滑变到另一个，中间有过程，不是瞬间跳。",
  },
  {
    id: "animation",
    zh: "动画",
    en: "Animation",
    category: "frontend",
    group: "动画",
    tagline: "一段会自己播放的动作，不必等人去点才开始。",
  },
  {
    id: "easing",
    zh: "缓动",
    en: "Easing",
    category: "frontend",
    group: "动画",
    tagline: "动的时候不是匀速，有加速和减速，看起来才像人推的。",
  },
  {
    id: "spring",
    zh: "弹性",
    en: "Spring",
    category: "frontend",
    group: "动画",
    tagline: "到了位置还会稍微过一点再弹回来，像弹簧。",
  },
  {
    id: "fade",
    zh: "渐入渐出",
    en: "Fade In / Out",
    category: "frontend",
    group: "动画",
    tagline: "靠慢慢显现或慢慢消失来换内容，不是瞬间切。",
  },
  {
    id: "hover",
    zh: "悬停",
    en: "Hover",
    category: "frontend",
    group: "鼠标",
    tagline: "鼠标停在上面还没点时，这块会换个样子。",
  },
  {
    id: "active",
    zh: "按下",
    en: "Active",
    category: "frontend",
    group: "鼠标",
    tagline: "按下去到松手之间那一下，用来告诉你点到了。",
  },
  {
    id: "focus",
    zh: "聚焦",
    en: "Focus",
    category: "frontend",
    group: "鼠标",
    tagline: "现在轮到这块接收键盘，要能看出现在停在哪。",
  },
  {
    id: "drag",
    zh: "拖拽",
    en: "Drag",
    category: "frontend",
    group: "鼠标",
    tagline: "按住一块东西挪位置，或把它丢进指定区域。",
  },
  {
    id: "disabled",
    zh: "禁用",
    en: "Disabled",
    category: "frontend",
    group: "鼠标",
    tagline: "现在点了不会做事，还得让人看得出为什么。",
  },
  {
    id: "cursor",
    zh: "鼠标指针",
    en: "Cursor",
    category: "frontend",
    group: "鼠标",
    tagline: "跟着鼠标走的那个形状，提前告诉你这里能干什么。",
  },
  {
    id: "selection",
    zh: "选中高亮",
    en: "Selection",
    category: "frontend",
    group: "鼠标",
    tagline: "划过的那截字换底色，好让人看清、好复制。",
  },
  {
    id: "domain",
    zh: "域名",
    en: "Domain",
    category: "backend",
    group: "网络与地址",
    tagline: "别人在地址栏里输入的那个好记的网站名字。",
  },
  {
    id: "dns",
    zh: "DNS",
    en: "",
    category: "backend",
    group: "网络与地址",
    tagline: "把网站名字翻译成机器能找到的数字地址。",
  },
  {
    id: "url",
    zh: "URL",
    en: "",
    category: "backend",
    group: "网络与地址",
    tagline: "地址栏里那一整串，精确指到某一个页面。",
  },
  {
    id: "http",
    zh: "HTTP",
    en: "",
    category: "backend",
    group: "网络与地址",
    tagline: "浏览器和网站之间传东西时用的说话规矩。",
  },
  {
    id: "cookie",
    zh: "Cookie",
    en: "",
    category: "backend",
    group: "网络与地址",
    tagline: "网站存在你浏览器里的小纸条，下次会自动带上。",
  },
  {
    id: "https",
    zh: "HTTPS",
    en: "",
    category: "backend",
    group: "网络与地址",
    tagline: "加了锁的 HTTP，路上的内容别人看不了。",
  },
  {
    id: "cdn",
    zh: "CDN",
    en: "",
    category: "backend",
    group: "网络与地址",
    tagline: "把图片和页面代码就近发给用户，外地打开更快。",
  },
  {
    id: "port",
    zh: "端口",
    en: "Port",
    category: "backend",
    group: "网络与地址",
    tagline: "同一台机器上区分不同服务的门牌号。",
  },
  {
    id: "redirect",
    zh: "重定向",
    en: "Redirect",
    category: "backend",
    group: "网络与地址",
    tagline: "打开旧地址时，自动把人带到新地址。",
  },
  {
    id: "api",
    zh: "API",
    en: "",
    category: "backend",
    group: "接口与数据",
    tagline: "网页向后台要数据、办事情时走的那扇门。",
  },
  {
    id: "json",
    zh: "JSON",
    en: "",
    category: "backend",
    group: "接口与数据",
    tagline: "用大括号把数据写成人和程序都能读的文本。",
  },
  {
    id: "cors",
    zh: "CORS",
    en: "",
    category: "backend",
    group: "接口与数据",
    tagline: "网页和接口不在同一地址时，浏览器可能拦住请求。",
  },
  {
    id: "data-validation",
    zh: "数据校验",
    en: "Validation",
    category: "backend",
    group: "接口与数据",
    tagline: "保存前先检查数据合不合格，不合格就拦下。",
  },
  {
    id: "api-key",
    zh: "API 密钥",
    en: "API Key",
    category: "backend",
    group: "接口与数据",
    tagline: "调用别人接口时出示的一串密钥，用来认出是你。",
  },
  {
    id: "browser-storage",
    zh: "浏览器存储",
    en: "Browser Storage",
    category: "backend",
    group: "数据库",
    tagline: "数据存在这台浏览器里，换设备或清记录就没了。",
  },
  {
    id: "database",
    zh: "数据库",
    en: "Database",
    category: "backend",
    group: "数据库",
    tagline: "所有人共用、关掉网页也不会丢的数据仓库。",
  },
  {
    id: "sql",
    zh: "SQL",
    en: "",
    category: "backend",
    group: "数据库",
    tagline: "向数据库提问和改数据时用的那门语言。",
  },
  {
    id: "backend",
    zh: "后端",
    en: "Backend",
    category: "backend",
    group: "后端开发",
    tagline: "网页看不见的那一层：存数据、做判断、对外说话。",
  },
  {
    id: "backend-framework",
    zh: "后端框架",
    en: "Backend Framework",
    category: "backend",
    group: "后端开发",
    tagline: "写后端时用的现成规矩和零件，不必从拆信封做起。",
  },
  {
    id: "route",
    zh: "路由与端点",
    en: "Route & Endpoint",
    category: "backend",
    group: "后端开发",
    tagline: "接口上每一条具体门口：这个地址、这个动作、办这件事。",
  },
  {
    id: "authentication",
    zh: "身份认证",
    en: "Authentication",
    category: "backend",
    group: "账号与权限",
    tagline: "先搞清楚「你是谁」，通常就是登录。",
  },
  {
    id: "authorization",
    zh: "权限控制",
    en: "Authorization",
    category: "backend",
    group: "账号与权限",
    tagline: "已经知道你是谁之后，再决定你能干什么。",
  },
  {
    id: "cache",
    zh: "缓存",
    en: "Cache",
    category: "backend",
    group: "上线与排错",
    tagline: "先留一份结果，下次少算一次、少下载一次。",
  },
  {
    id: "seo",
    zh: "SEO",
    en: "",
    category: "backend",
    group: "上线与排错",
    tagline: "让搜索引擎能找到、读懂、把你的页推给陌生人。",
  },
  {
    id: "canonical-url",
    zh: "规范网址",
    en: "Canonical URL",
    category: "backend",
    group: "上线与排错",
    tagline: "同一页有好几个地址时，指定哪一个才算正式的。",
  },
  {
    id: "xml-sitemap",
    zh: "XML 站点地图",
    en: "XML Sitemap",
    category: "backend",
    group: "上线与排错",
    tagline: "给搜索引擎的网址清单，不是给人逛的目录。",
  },
  {
    id: "robots-txt",
    zh: "Robots.txt",
    en: "",
    category: "backend",
    group: "上线与排错",
    tagline: "放在网站根上的说明书，告诉自动来转的程序哪些能进。",
  },
  {
    id: "not-found-page",
    zh: "找不到页面",
    en: "Not Found Page",
    category: "backend",
    group: "上线与排错",
    tagline: "地址不对或页面没了时，给人看的那一页说明。",
  },
  {
    id: "env-var",
    zh: "环境变量",
    en: "Env Var",
    category: "backend",
    group: "上线与排错",
    tagline: "随运行环境而变的配置，密钥不该写进代码。",
  },
  {
    id: "deployment",
    zh: "部署上线",
    en: "Deployment",
    category: "backend",
    group: "上线与排错",
    tagline: "把你电脑上能跑的，变成别人在网上能打开的。",
  },
  {
    id: "web-hosting",
    zh: "网站托管",
    en: "Web Hosting",
    category: "backend",
    group: "上线与排错",
    tagline: "把网站放在一台一直在线的地方，供人打开。",
  },
  {
    id: "cd",
    zh: "持续交付 / 持续部署",
    en: "CD",
    category: "backend",
    group: "上线与排错",
    tagline: "测试通过之后，把新版本送到用户能碰到的地方。",
  },
  {
    id: "staging",
    zh: "预发布环境",
    en: "Staging",
    category: "backend",
    group: "上线与排错",
    tagline: "长得像正式站点、只给内部试的那一套。",
  },
  {
    id: "monitoring",
    zh: "监控",
    en: "Monitoring",
    category: "backend",
    group: "上线与排错",
    tagline: "自己先发现网站慢了、挂了，而不是等用户来问。",
  },
  {
    id: "rollback",
    zh: "回滚",
    en: "Rollback",
    category: "backend",
    group: "上线与排错",
    tagline: "新版本闯祸时，切回上一版还能用的。",
  },
  {
    id: "feature-flag",
    zh: "功能开关",
    en: "Feature Flag",
    category: "backend",
    group: "上线与排错",
    tagline: "不发新版本也能打开或关上某项功能。",
  },
  {
    id: "canary-release",
    zh: "金丝雀发布",
    en: "Canary Release",
    category: "backend",
    group: "上线与排错",
    tagline: "先让一小部分人碰到新版本，没问题再放开。",
  },
  {
    id: "blue-green-deployment",
    zh: "蓝绿部署",
    en: "Blue-Green Deployment",
    category: "backend",
    group: "上线与排错",
    tagline: "旁边准备一套完整新环境，就绪后一次性切换。",
  },
  {
    id: "serverless",
    zh: "Serverless",
    en: "",
    category: "backend",
    group: "上线与排错",
    tagline: "你不租、不养那台机器，有人来了才跑你的程序。",
  },
  {
    id: "server-log",
    zh: "服务端日志",
    en: "Server Logs",
    category: "backend",
    group: "上线与排错",
    tagline: "服务器记下的流水账：谁来过、做成了没、哪句报错。",
  },
  {
    id: "user-story",
    zh: "用户故事",
    en: "User Story",
    category: "product",
    group: "用户与需求",
    tagline: "用谁、卡在哪、做成了怎样来决定做不做。",
  },
  {
    id: "use-case",
    zh: "用户用例",
    en: "Use Case",
    category: "product",
    group: "用户与需求",
    tagline: "把一件事从发起到成功或失败逐步写完。",
  },
  {
    id: "user-flow",
    zh: "用户流程",
    en: "User Flow",
    category: "product",
    group: "用户与需求",
    tagline: "人从进来到办完经过哪几页、哪几个分岔。",
  },
  {
    id: "user-journey",
    zh: "用户旅程",
    en: "User Journey",
    category: "product",
    group: "用户与需求",
    tagline: "把听说、等待、卡住和点进去之后放同一条线。",
  },
  {
    id: "prd",
    zh: "PRD",
    en: "",
    category: "product",
    group: "产品规划",
    tagline: "把做什么、不做什么、做到哪算完写成说明。",
  },
  {
    id: "mvp",
    zh: "MVP",
    en: "",
    category: "product",
    group: "产品规划",
    tagline: "先做刚够拿去给真人用的最小一版。",
  },
  {
    id: "product-backlog",
    zh: "产品待办列表",
    en: "Product Backlog",
    category: "product",
    group: "产品规划",
    tagline: "所有可能做、还没答应做完的事排成的总单。",
  },
  {
    id: "product-roadmap",
    zh: "产品路线图",
    en: "Product Roadmap",
    category: "product",
    group: "产品规划",
    tagline: "按阶段写出接下来主攻什么、故意不做什么。",
  },
  {
    id: "gantt-chart",
    zh: "甘特图",
    en: "Gantt Chart",
    category: "product",
    group: "产品规划",
    tagline: "把任务画在日历上，谁先谁后、拖了会挡谁。",
  },
  {
    id: "wireframe",
    zh: "线框图",
    en: "Wireframe",
    category: "product",
    group: "产品规划",
    tagline: "先用灰块排出这一页有什么、放哪，不上颜色。",
  },
  {
    id: "moodboard",
    zh: "情绪板",
    en: "Moodboard",
    category: "product",
    group: "产品规划",
    tagline: "把喜欢的和明确不要的样子拼在一页。",
  },
  {
    id: "ab-test",
    zh: "A/B 测试",
    en: "A/B Test",
    category: "product",
    group: "数据与验证",
    tagline: "同时放两个版本，按同一件事比哪个更好。",
  },
  {
    id: "conversion-funnel",
    zh: "转化漏斗",
    en: "Conversion Funnel",
    category: "product",
    group: "数据与验证",
    tagline: "把办成一件事拆成几步，看人主要从哪一步离开。",
  },
  {
    id: "crud",
    zh: "增删改查",
    en: "CRUD",
    category: "product",
    group: "数据与验证",
    tagline: "对同一批记录做新增、查看、修改、删除。",
  },
  {
    id: "field",
    zh: "字段",
    en: "Field",
    category: "product",
    group: "数据与验证",
    tagline: "每一条记录上单独的一栏，比如姓名或金额。",
  },
  {
    id: "data-type",
    zh: "数据类型",
    en: "Data Type",
    category: "product",
    group: "数据与验证",
    tagline: "这一栏是文字、数字、日期还是是非，决定能怎么用。",
  },
  {
    id: "import-export",
    zh: "导入导出",
    en: "Import & Export",
    category: "product",
    group: "数据与验证",
    tagline: "把记录整批送进来，或整批拿出去给表格软件。",
  },
  {
    id: "terminal",
    zh: "终端命令行",
    en: "Terminal",
    category: "technology",
    group: "开发工具",
    tagline: "对着电脑打一行字，让它去装包、跑检查。",
  },
  {
    id: "browser-devtools",
    zh: "浏览器开发者工具",
    en: "Browser DevTools",
    category: "technology",
    group: "开发工具",
    tagline: "浏览器自带的检查箱，看报错和这一页的零件。",
  },
  {
    id: "npm",
    zh: "npm",
    en: "",
    category: "technology",
    group: "开发工具",
    tagline: "装别人写好的 JavaScript 代码包的商店和工具。",
  },
  {
    id: "build",
    zh: "构建",
    en: "Build",
    category: "technology",
    group: "开发工具",
    tagline: "把开发时的代码变成浏览器能直接打开的文件。",
  },
  {
    id: "ci",
    zh: "持续集成",
    en: "CI",
    category: "technology",
    group: "开发工具",
    tagline: "每次改完，让另一台机器自动跑检查。",
  },
  {
    id: "lint",
    zh: "代码规范检查",
    en: "Lint",
    category: "technology",
    group: "开发工具",
    tagline: "自动挑格式和常见写错，不必等人工盯空格。",
  },
  {
    id: "acceptance-criteria",
    zh: "验收标准",
    en: "Acceptance Criteria",
    category: "technology",
    group: "测试",
    tagline: "能当场核对的句子：怎样才算做完、怎样才算对。",
  },
  {
    id: "test-case",
    zh: "测试用例",
    en: "Test Case",
    category: "technology",
    group: "测试",
    tagline: "一组「怎么操作、应当看到什么」的核对步骤。",
  },
  {
    id: "unit-test",
    zh: "单元测试",
    en: "Unit Test",
    category: "technology",
    group: "测试",
    tagline: "只测一小块规则，不打开整个网站。",
  },
  {
    id: "integration-test",
    zh: "集成测试",
    en: "Integration Test",
    category: "technology",
    group: "测试",
    tagline: "把相邻几块接上一起测，看拼得上拼不上。",
  },
  {
    id: "e2e-test",
    zh: "端到端测试",
    en: "End-to-End Test",
    category: "technology",
    group: "测试",
    tagline: "像真人一样打开页面，从进门点到事情做完。",
  },
  {
    id: "smoke-test",
    zh: "冒烟测试",
    en: "Smoke Test",
    category: "technology",
    group: "测试",
    tagline: "先确认打得开、最要紧的那一下还能用。",
  },
  {
    id: "regression-test",
    zh: "回归测试",
    en: "Regression Test",
    category: "technology",
    group: "测试",
    tagline: "改完新的，再测以前能用的有没有坏。",
  },
  {
    id: "test-coverage",
    zh: "测试覆盖率",
    en: "Test Coverage",
    category: "technology",
    group: "测试",
    tagline: "测试跑过了多少代码，不是「测得有多好」。",
  },
  {
    id: "test-double",
    zh: "测试替身",
    en: "Test Double",
    category: "technology",
    group: "测试",
    tagline: "测试里顶替真邻居的假东西，比如假发短信。",
  },
  {
    id: "test-fixture",
    zh: "测试数据与 Fixture",
    en: "Test Data and Fixture",
    category: "technology",
    group: "测试",
    tagline: "测试开始前摆好的那份固定假数据。",
  },
  {
    id: "flaky-test",
    zh: "不稳定测试",
    en: "Flaky Test",
    category: "technology",
    group: "测试",
    tagline: "代码没改，测试却有时过有时挂。",
  },
  {
    id: "tech-stack",
    zh: "技术栈",
    en: "Tech Stack",
    category: "technology",
    group: "技术栈",
    tagline: "做这个产品时选中的语言、页面写法和工具组合。",
  },
  {
    id: "javascript",
    zh: "JavaScript",
    en: "",
    category: "technology",
    group: "编程语言",
    tagline: "让网页听懂点击和输入的语言，浏览器只认它。",
  },
  {
    id: "typescript",
    zh: "TypeScript",
    en: "",
    category: "technology",
    group: "编程语言",
    tagline: "给 JavaScript 补上「这是数字还是文字」的检查。",
  },
  {
    id: "python",
    zh: "Python",
    en: "",
    category: "technology",
    group: "编程语言",
    tagline: "在自己电脑上跑、常用来处理文件和表格的语言。",
  },
  {
    id: "react",
    zh: "React",
    en: "",
    category: "technology",
    group: "前端框架",
    tagline: "把网页拆成可复用零件来搭的一套写法。",
  },
  {
    id: "vue",
    zh: "Vue",
    en: "",
    category: "technology",
    group: "前端框架",
    tagline: "另一套用零件搭网页的写法，不能当 React 用。",
  },
  {
    id: "nextjs",
    zh: "Next.js",
    en: "",
    category: "technology",
    group: "前端框架",
    tagline: "在 React 上补网址、打开就能读的字、给搜索引擎看。",
  },
  {
    id: "tailwind-css",
    zh: "Tailwind CSS",
    en: "",
    category: "technology",
    group: "CSS 与组件",
    tagline: "把间距、颜色、字号写成标签上现成短名的做法。",
  },
  {
    id: "shadcn-ui",
    zh: "shadcn/ui",
    en: "",
    category: "technology",
    group: "CSS 与组件",
    tagline: "把按钮、对话框的代码复制进项目、归你改的做法。",
  },
  {
    id: "ai-basics",
    zh: "AI 应用基础",
    en: "AI Application Basics",
    category: "ai",
    group: "AI 基础",
    tagline: "把别人家的 AI 接到你自己的网站或小工具里。",
  },
  {
    id: "ai-hallucination",
    zh: "AI 幻觉",
    en: "AI Hallucination",
    category: "ai",
    group: "AI 基础",
    tagline: "AI 说得像真的，其实是它编出来的。",
  },
  {
    id: "vibe-coding",
    zh: "Vibe Coding",
    en: "",
    category: "ai",
    group: "AI 基础",
    tagline: "用说话的方式让 AI 帮你写出能跑的东西。",
  },
  {
    id: "multimodal",
    zh: "多模态",
    en: "Multimodal AI",
    category: "ai",
    group: "AI 基础",
    tagline: "AI 不只读字，还能看图、听声音。",
  },
  {
    id: "context-engineering",
    zh: "上下文工程",
    en: "Context Engineering",
    category: "ai",
    group: "上下文",
    tagline: "决定这一次到底塞给 AI 哪些材料。",
  },
  {
    id: "token",
    zh: "Token",
    en: "",
    category: "ai",
    group: "上下文",
    tagline: "AI 计费和记忆用的最小文字块。",
  },
  {
    id: "context-window",
    zh: "上下文窗口",
    en: "Context Window",
    category: "ai",
    group: "上下文",
    tagline: "一次对话里 AI 能同时看见的上限。",
  },
  {
    id: "system-prompt",
    zh: "系统提示词",
    en: "System Prompt",
    category: "ai",
    group: "上下文",
    tagline: "写给 AI 的长期规矩，不是这一句闲聊。",
  },
  {
    id: "conversation-history",
    zh: "对话历史",
    en: "Conversation History",
    category: "ai",
    group: "上下文",
    tagline: "聊天框里那些旧消息，下次还会再寄一遍。",
  },
  {
    id: "prompt",
    zh: "提示词",
    en: "Prompt",
    category: "ai",
    group: "上下文",
    tagline: "你写给 AI 的那一段具体吩咐。",
  },
  {
    id: "stateless-request",
    zh: "无状态请求",
    en: "Stateless Request",
    category: "ai",
    group: "请求与输出",
    tagline: "每次提问，AI 只看见你这次附上的内容。",
  },
  {
    id: "structured-output",
    zh: "结构化输出",
    en: "Structured Output",
    category: "ai",
    group: "请求与输出",
    tagline: "让 AI 按固定格子吐结果，而不是一长段散文。",
  },
  {
    id: "streaming-response",
    zh: "流式响应",
    en: "Streaming Response",
    category: "ai",
    group: "请求与输出",
    tagline: "字一个接一个往外蹦，不用等整篇写完。",
  },
  {
    id: "ai-agent",
    zh: "AI Agent",
    en: "",
    category: "ai",
    group: "Agent 与工具",
    tagline: "给目标，让 AI 自己选工具、分步把事做完。",
  },
  {
    id: "harness-engineering",
    zh: "Agent 运行框架工程",
    en: "Harness Engineering",
    category: "ai",
    group: "Agent 与工具",
    tagline: "围着 AI 搭的那套规矩、工具和重试办法。",
  },
  {
    id: "human-in-the-loop",
    zh: "人在回路",
    en: "Human-in-the-loop",
    category: "ai",
    group: "Agent 与工具",
    tagline: "关键步骤必须等人点头，AI 不能自己拍板。",
  },
  {
    id: "mcp",
    zh: "MCP",
    en: "Model Context Protocol",
    category: "ai",
    group: "Agent 与工具",
    tagline: "一种让 AI 接上外部工具和资料的通用插头。",
  },
  {
    id: "skill",
    zh: "Skill",
    en: "",
    category: "ai",
    group: "Agent 与工具",
    tagline: "一套可反复调用的做法说明，不必每次重教。",
  },
  {
    id: "sub-agent",
    zh: "Sub-agent",
    en: "",
    category: "ai",
    group: "Agent 与工具",
    tagline: "大任务拆给另一个专职的小助手去办。",
  },
  {
    id: "tool-calling",
    zh: "工具调用",
    en: "Tool Calling",
    category: "ai",
    group: "Agent 与工具",
    tagline: "AI 不只说话，还会点名调用一个外部动作。",
  },
  {
    id: "react-pattern",
    zh: "ReAct",
    en: "",
    category: "ai",
    group: "Agent 与工具",
    tagline: "先想一步、再动手、看结果，再决定下一步。",
  },
  {
    id: "agent-loop",
    zh: "Agent 循环",
    en: "Agent Loop",
    category: "ai",
    group: "Agent 与工具",
    tagline: "AI 反复「想—做—看」直到完成或停下。",
  },
  {
    id: "response-speed",
    zh: "TTFT / TPS",
    en: "",
    category: "ai",
    group: "性能与成本",
    tagline: "第一个字等多久，以及后面字蹦得多快。",
  },
  {
    id: "token-cost",
    zh: "Token 用量与成本",
    en: "Token Usage & Cost",
    category: "ai",
    group: "性能与成本",
    tagline: "按文字块计费：发给它的、它吐出来的都算。",
  },
  {
    id: "rate-limit",
    zh: "速率限制",
    en: "Rate Limit",
    category: "ai",
    group: "性能与成本",
    tagline: "短时间问太多次，对方会暂时拒收。",
  },
  {
    id: "git",
    zh: "Git",
    en: "",
    category: "git",
    group: "Git",
    tagline: "记下每一次能回头的存档，AI 改崩了还能退。",
  },
  {
    id: "commit",
    zh: "提交",
    en: "Commit",
    category: "git",
    group: "Git",
    tagline: "把这一刻打成一包可回头的存档。",
  },
  {
    id: "branch",
    zh: "分支",
    en: "Branch",
    category: "git",
    group: "Git",
    tagline: "从正在用的版本分出去的一条平行线。",
  },
  {
    id: "merge",
    zh: "合并",
    en: "Merge",
    category: "git",
    group: "Git",
    tagline: "把另一条线上的改动并进当前这条。",
  },
  {
    id: "pull",
    zh: "拉取",
    en: "Pull",
    category: "git",
    group: "Git",
    tagline: "把网上那份的新存档取回到自己电脑。",
  },
  {
    id: "push",
    zh: "推送",
    en: "Push",
    category: "git",
    group: "Git",
    tagline: "把自己电脑上的存档送到网上那份。",
  },
  {
    id: "clone",
    zh: "克隆",
    en: "Clone",
    category: "git",
    group: "Git",
    tagline: "第一次把带历史的项目完整拷到电脑上。",
  },
  {
    id: "pull-request",
    zh: "合并请求",
    en: "Pull Request",
    category: "git",
    group: "Git",
    tagline: "请人看过再把这条线并进正式版。",
  },
  {
    id: "worktree",
    zh: "工作树",
    en: "Worktree",
    category: "git",
    group: "Git",
    tagline: "同一份历史上再开一个文件夹干活。",
  },
  {
    id: "stash",
    zh: "贮藏",
    en: "Stash",
    category: "git",
    group: "Git",
    tagline: "把还没存档的改动临时收进抽屉。",
  },
  {
    id: "gitignore",
    zh: "忽略文件",
    en: ".gitignore",
    category: "git",
    group: "Git",
    tagline: "告诉 Git 哪些文件不要记、不要提交。",
  },
  {
    id: "diff",
    zh: "差异对比",
    en: "Diff",
    category: "git",
    group: "Git",
    tagline: "一行一行标出这次加了什么、删了什么。",
  },
  {
    id: "style-minimal",
    zh: "现代简约",
    en: "Minimalism",
    category: "design",
    group: "设计风格",
    tagline: "少颜色、多留白，让内容和主按钮自己说话。",
  },
  {
    id: "style-apple",
    zh: "苹果风",
    en: "Apple HIG",
    category: "design",
    group: "设计风格",
    tagline: "大图、大字、大片空，克制得像苹果的产品页。",
  },
  {
    id: "style-notion",
    zh: "Notion 风",
    en: "Notion Style",
    category: "design",
    group: "设计风格",
    tagline: "像一本打开的笔记本：字是主角，装饰尽量少。",
  },
  {
    id: "style-bento",
    zh: "Bento 便当格",
    en: "Bento Grid",
    category: "design",
    group: "设计风格",
    tagline: "大小不一的格子拼成一盘，像便当格各装一样菜。",
  },
  {
    id: "style-glass",
    zh: "玻璃拟态",
    en: "Glassmorphism",
    category: "design",
    group: "设计风格",
    tagline: "半透明磨砂板叠在花背景上，后面隐约透出来。",
  },
  {
    id: "style-brutalism",
    zh: "新粗野",
    en: "Neo-Brutalism",
    category: "design",
    group: "设计风格",
    tagline: "粗黑边、硬影子、大色块，故意看起来冲。",
  },
  {
    id: "style-swiss",
    zh: "瑞士排版",
    en: "Swiss Style",
    category: "design",
    group: "设计风格",
    tagline: "网格、大号黑体、严格对齐，像瑞士海报。",
  },
  {
    id: "style-editorial",
    zh: "杂志编辑风",
    en: "Editorial",
    category: "design",
    group: "设计风格",
    tagline: "像翻杂志：大图咬着字，引文突出，栏宽有戏剧。",
  },
  {
    id: "style-skeuomorphism",
    zh: "拟物化",
    en: "Skeuomorphism",
    category: "design",
    group: "设计风格",
    tagline: "按钮画成真按钮，皮面木纹，像实物的电子版。",
  },
  {
    id: "style-flat",
    zh: "扁平化",
    en: "Flat Design",
    category: "design",
    group: "设计风格",
    tagline: "去掉立体和材质，用纯色块和简单图形把界面摊平。",
  },
  {
    id: "style-material",
    zh: "材料设计",
    en: "Material Design",
    category: "design",
    group: "设计风格",
    tagline: "卡片像一层纸，影子表示叠了多高，点下去散开一圈。",
  },
  {
    id: "style-neumorphism",
    zh: "新拟态",
    en: "Neumorphism",
    category: "design",
    group: "设计风格",
    tagline: "按钮跟背景同色，靠一明一暗的软影鼓起来。",
  },
  {
    id: "style-saas",
    zh: "SaaS 产品官网",
    en: "SaaS Marketing Site",
    category: "design",
    group: "设计风格",
    tagline: "软件官网那一套：首屏、功能、客户标志、定价。",
  },
  {
    id: "style-enterprise",
    zh: "B2B 企业官网",
    en: "B2B Corporate Site",
    category: "design",
    group: "设计风格",
    tagline: "卖给公司看的官网：稳、可信、方便找人和案例。",
  },
  {
    id: "style-commerce",
    zh: "DTC 品牌电商",
    en: "DTC E-commerce",
    category: "design",
    group: "设计风格",
    tagline: "品牌自己开的店：大图讲故事，路通向结算。",
  },
  {
    id: "style-dark-tech",
    zh: "深色界面",
    en: "Dark UI",
    category: "design",
    group: "设计风格",
    tagline: "产品本来就是深底浅字，不是晚上才涂一层黑。",
  },
  {
    id: "style-playful",
    zh: "趣味插画",
    en: "Playful Illustration",
    category: "design",
    group: "设计风格",
    tagline: "自绘角色和插画当主角，颜色亮，可以开玩笑。",
  },
  {
    id: "style-organic",
    zh: "有机设计",
    en: "Organic Design",
    category: "design",
    group: "设计风格",
    tagline: "泥土色、圆润边、像手作，少用冷冰冰的直线格。",
  },
  {
    id: "style-y2k",
    zh: "Y2K",
    en: "",
    category: "design",
    group: "设计风格",
    tagline: "千禧年那套：金属光、泡泡、半透明塑料。",
  },
  {
    id: "style-memphis",
    zh: "孟菲斯",
    en: "Memphis",
    category: "design",
    group: "设计风格",
    tagline: "八十年代几何积木：波浪线、波点、撞色，很闹。",
  },
  {
    id: "style-terminal",
    zh: "终端极客风",
    en: "Terminal Aesthetic",
    category: "design",
    group: "设计风格",
    tagline: "黑底绿字、每个字母一样宽，像在敲命令。",
  },
  {
    id: "style-wabisabi",
    zh: "日式侘寂",
    en: "Wabi-sabi",
    category: "design",
    group: "设计风格",
    tagline: "素、旧、不对称，留出空，像用了很久的纸和陶。",
  },
  {
    id: "style-bauhaus",
    zh: "包豪斯",
    en: "Bauhaus",
    category: "design",
    group: "设计风格",
    tagline: "圆、方、三角和三原色都得有用，别只当贴纸。",
  },
  {
    id: "style-art-deco",
    zh: "装饰艺术",
    en: "Art Deco",
    category: "design",
    group: "设计风格",
    tagline: "对称、扇形纹、金和黑，像老剧院海报那种排场。",
  },
];
